### ISSUE TITLE
Difficulty migrating to new version, React + plugins

### ISSUE THREAD

**Issue by rbracco** [katspaugh/wavesurfer.ts#49] opened 2023-04-25 15:46 UTC
I've tried upgrading from 6.6.3 to the alpha release but was running into a lot of issues, especially surrounding plugins. I found the react example + hook extremely helpful, but it would be great if the React example could also use a plugin so that we can see how to properly register/update plugins. For now I think it is a bit too early for me to migrate, here are a couple issues I experienced.

1. The regions example doesn't loop the selected region most of the time, even when the "loop regions on click" is checked. It does maybe 20% of the time and is seemingly random. 
2. Is there a reason `region.play()` now needs to be called with `setTimeout`, I believe it is currently undocumented but didn't seem to make a difference in my code.
3. I was having difficulty getting a single region to play using a button with an `onClick` callback that looks like this
```
  const playRegion = () => {
    let region = wsRegions.regions[0];
    setTimeout(() => region.play(), 10)
  }
```
On first click it would jump to the start of the region but not play, and on the 2nd click it would play but wouldn't stop at the end of the region and would continue to the end of the audio.

**Comment by katspaugh** [comment] 2023-04-25 17:15
Thanks for the feedback.

Adding plugins to the react example is a good idea.

Regions don’t necessarily have to play in a timeout, it’s related to a workaround for Safari. I’ll investigate the issues you mentioned.

**Comment by katspaugh** [comment] 2023-04-25 19:38
I've added a Timeline to the [React example](https://wavesurfer-ts.pages.dev/tutorial/#/examples/react.js).
It's passed in the plugins config bug you can also call `wavesurfer.registerPlugin` to add a plugin dynamically.

Also removed the confusing setTimeout's. I couldn't reproduce a region not looping yet. Does it happen for you in the [Regions example](https://wavesurfer-ts.pages.dev/tutorial/#/examples/regions.js)?

**Comment by rbracco** [comment] 2023-04-25 20:12
Thank you! I'll check it out as soon as I'm able. I was experiencing it not
looping in the Regions demo using the latest version of Google Chrome, I'll
try to play around with it more tomorrow.

**Comment by katspaugh** [comment] 2023-04-26 04:05
Cool, thank you! I’ll close this then, please feel free to reopen if you notice it again.

**Closed by katspaugh** 2023-04-26 04:05 UTC
